# Generated by Django 5.1.2 on 2024-10-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='gallery',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
