# Generated by Django 5.1.2 on 2024-11-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='seats_numbers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
