# Generated by Django 5.1.2 on 2024-11-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_location_seats_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.TextField(max_length=30),
        ),
    ]
