# Generated by Django 5.1.2 on 2024-11-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_location_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20, unique=True)),
                ('lastname', models.CharField(max_length=20, unique=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='poze_invitati/')),
                ('cuisine_preference', models.CharField(blank=True, max_length=50, null=True)),
                ('allergens', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=60, unique=True)),
                ('item_cuisine', models.CharField(max_length=20, unique=True)),
                ('item_vegan', models.BooleanField(default=False)),
                ('allergens', models.JSONField(default=list)),
            ],
        ),
    ]
