# Generated by Django 5.1.2 on 2024-11-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_guests_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='item_cuisine',
            field=models.CharField(max_length=20),
        ),
    ]
