# Generated by Django 5.1.2 on 2024-11-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendinguser',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pending_users/'),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
