# Generated by Django 5.1.2 on 2024-11-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_pendinguser_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
