# Generated by Django 5.1.2 on 2024-11-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_menu_item_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='allergens',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
