# Generated by Django 5.1.2 on 2024-11-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_pendinguser_is_confirmed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingUser',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
