# Generated by Django 5.1.2 on 2024-11-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_guests_allergens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='allergens',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
