# Generated by Django 5.1.2 on 2024-11-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_menu_allergens'),
    ]

    operations = [
        migrations.AddField(
            model_name='guests',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
    ]
