# Generated by Django 5.1.2 on 2024-11-18 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_guests_vegan'),
    ]

    operations = [
        migrations.AddField(
            model_name='guests',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='guests',
            name='firstname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='guests',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1),
        ),
        migrations.AlterField(
            model_name='guests',
            name='lastname',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guests', models.ManyToManyField(blank=True, related_name='events', to='base.guests')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.location')),
            ],
        ),
        migrations.CreateModel(
            name='EventMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=80)),
                ('item_cuisine', models.CharField(max_length=20)),
                ('item_vegan', models.BooleanField(default=False)),
                ('allergens', models.JSONField(blank=True, default=list, null=True)),
                ('item_picture', models.ImageField(blank=True, null=True, upload_to='event_menus/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='base.event')),
            ],
        ),
    ]
