# Generated by Django 5.1.2 on 2024-11-24 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_tasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
