# Generated by Django 5.1.2 on 2024-12-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_event_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='types',
            field=models.ManyToManyField(blank=True, to='base.type'),
        ),
    ]
