# Generated by Django 5.1.2 on 2024-12-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_location_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='cost',
            field=models.IntegerField(default=3000),
        ),
    ]
