# Generated by Django 5.1.2 on 2024-12-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_location_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cost',
            field=models.IntegerField(default=3000),
        ),
        migrations.AddField(
            model_name='profile',
            name='number',
            field=models.CharField(default='+(40) 748364823', max_length=15),
        ),
    ]
