# Generated by Django 5.1.2 on 2024-12-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_event_cost_profile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='number',
            field=models.CharField(default='+(40) 74 83 64 823', max_length=20),
        ),
    ]
