# Generated by Django 4.2.16 on 2025-01-05 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_event_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.location')),
            ],
        ),
    ]
