# Generated by Django 5.1.2 on 2025-01-08 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_eventhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventHistory',
        ),
    ]
