# Generated by Django 5.1.2 on 2025-01-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_eventhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
