# Generated by Django 5.1.2 on 2025-01-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_event_is_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventhistory',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled')], default='active', max_length=20),
        ),
    ]
