# Generated by Django 5.1.2 on 2025-01-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_eventhistory_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventhistory',
            name='status',
        ),
    ]
