# Generated by Django 5.1.2 on 2025-01-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('os_name', models.CharField(max_length=255)),
                ('last_access_time', models.DateTimeField(auto_now=True)),
                ('user_agent', models.CharField(max_length=512)),
            ],
        ),
    ]
