# Generated by Django 5.1.2 on 2025-01-11 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_remove_profile_linkedin_profile_linkedin_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='linkedin_link',
            new_name='work_link',
        ),
    ]
