# Generated by Django 5.1.2 on 2025-01-11 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_rename_linkedin_link_profile_work_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='work_link',
            new_name='linkedin',
        ),
    ]
