# Generated by Django 5.1.2 on 2025-01-11 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_rename_work_link_profile_linkedin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='linkedin',
            new_name='work_link',
        ),
    ]
