# Generated by Django 5.1.2 on 2025-01-11 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_rename_linkedin_profile_work_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='google',
            new_name='google_link',
        ),
    ]
