# Generated by Django 4.2.16 on 2025-01-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_rename_google_profile_google_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('oraganizer', 'Organizer'), ('guest', 'Guest'), ('staff', 'Staff')], default='guest', max_length=20),
        ),
        migrations.DeleteModel(
            name='PersonalLocation',
        ),
    ]
