# Generated by Django 4.2.16 on 2025-01-13 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_profile_user_type_delete_personallocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guests',
            name='email',
        ),
        migrations.RemoveField(
            model_name='guests',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='guests',
            name='lastname',
        ),
    ]
