# Generated by Django 4.2.16 on 2025-01-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_remove_guests_email_remove_guests_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('organizer', 'Organizer'), ('guest', 'Guest'), ('staff', 'Staff')], default='guest', max_length=20),
        ),
    ]
