# Generated by Django 4.2.16 on 2025-01-15 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='guests',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_profile', to='base.profile'),
        ),
        migrations.AlterField(
            model_name='guests',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1, null=True),
        ),
    ]
