# Generated by Django 5.1.2 on 2025-01-15 16:06

import base.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from base.models import User

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_alter_profile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, default=User.objects.get_or_create(username='defaultuser')[0]
, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
