# Generated by Django 5.1.2 on 2025-01-29 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_alter_profile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('created_event', 'Created Event'), ('updated_event', 'Updated Event'), ('deleted_event', 'Deleted Event'), ('created_location', 'Created Location'), ('updated_location', 'Updated Location'), ('deleted_location', 'Deleted Location'), ('updated_profile', 'Updated Profile')], max_length=50)),
                ('target_object_id', models.PositiveIntegerField()),
                ('target_model', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='profile',
            name='unique_approved_profile',
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
