# Generated by Django 5.1.2 on 2025-01-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_notification_remove_profile_unique_approved_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_object_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
