# Generated by Django 5.1.2 on 2025-02-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_alter_event_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='last_location_update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
