# Generated by Django 5.1.2 on 2025-02-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_budget_last_location_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='initial_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='budget',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='location',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=3000, max_digits=12),
        ),
    ]
