# Generated by Django 5.1.2 on 2025-02-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_budget_initial_budget_budget_profit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='profit',
        ),
        migrations.AddField(
            model_name='budget',
            name='final_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
