# Generated by Django 5.1.2 on 2025-02-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_remove_budget_profit_budget_final_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='final_budget',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=12),
        ),
    ]
