# Generated by Django 5.1.2 on 2025-02-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_alter_budget_final_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
