# Generated by Django 4.2.16 on 2025-02-05 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_guests_profile_alter_guests_gender'),
        ('base', '0064_companyprofit'),
    ]

    operations = [
    ]
