# Generated by Django 4.2.16 on 2025-02-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_merge_20250205_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='guests',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
