# Generated by Django 5.1.2 on 2025-02-07 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_merge_20250205_2040'),
        ('base', '0066_guests_state'),
    ]

    operations = [
    ]
