# Generated by Django 5.1.2 on 2025-02-07 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_userprofile'),
        ('base', '0067_merge_0065_merge_20250205_2040_0066_guests_state'),
    ]

    operations = [
    ]
