# Generated by Django 4.2.16 on 2025-02-10 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_merge_0065_merge_20250205_2040_0066_guests_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='base.location')),
            ],
        ),
    ]
