# Generated by Django 5.1.2 on 2025-03-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0071_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_type',
            field=models.CharField(choices=[('created_event', 'Created Event'), ('updated_event', 'Updated Event'), ('deleted_event', 'Deleted Event'), ('created_location', 'Created Location'), ('updated_location', 'Updated Location'), ('deleted_location', 'Deleted Location'), ('updated_profile', 'Updated Profile'), ('completed_event', 'Completed Event')], max_length=50),
        ),
    ]
