# Generated by Django 5.1.2 on 2025-03-26 12:23

import base.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_allergen_added_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='at_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.location'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='item_picture',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.menu_item_upload_path),
        ),
        migrations.CreateModel(
            name='GuestMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='base.event')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest', to=settings.AUTH_USER_MODEL)),
                ('menu_choices', models.ManyToManyField(blank=True, related_name='guests', to='base.menu')),
            ],
        ),
    ]
