# Generated by Django 4.2.16 on 2025-03-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0076_menu_at_location_alter_menu_item_picture_guestmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='poze_invitati/male.jpg', null=True, upload_to='profile_photos/'),
        ),
    ]
