# Generated by Django 4.2.16 on 2025-03-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_alter_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='allergens',
        ),
        migrations.AddField(
            model_name='menu',
            name='allergens',
            field=models.ManyToManyField(blank=True, to='base.allergen'),
        ),
    ]
