# Generated by Django 4.2.16 on 2025-04-03 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_profile_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestmenu',
            name='location_menu',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='location_menu', to='base.location'),
        ),
    ]
