# Generated by Django 4.2.16 on 2025-04-08 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0081_eventpost_postimage_postcomment_postlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
