# Generated by Django 4.2.16 on 2025-04-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0082_alter_eventpost_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guests',
            name='allergens',
        ),
        migrations.AddField(
            model_name='guests',
            name='allergens',
            field=models.ManyToManyField(blank=True, to='base.allergen'),
        ),
    ]
