# Generated by Django 5.1.2 on 2025-05-24 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0083_remove_guests_allergens_guests_allergens'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.event'),
        ),
    ]
