# Generated by Django 5.2.2 on 2025-06-06 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0084_log_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('capacity', models.IntegerField(help_text='Number of seats at this table')),
                ('shape', models.CharField(choices=[('round', 'Round'), ('rectangle', 'Rectangle'), ('square', 'Square')], default='round', max_length=20)),
                ('position_x', models.IntegerField(help_text='X position in the room layout')),
                ('position_y', models.IntegerField(help_text='Y position in the room layout')),
                ('is_reserved', models.BooleanField(default=False, help_text='Reserved for special groups (e.g., bride and groom)')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the table', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='base.location')),
            ],
            options={
                'ordering': ['table_number'],
                'unique_together': {('location', 'table_number')},
            },
        ),
        migrations.CreateModel(
            name='TableArrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField(help_text='Specific seat number at the table')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('special_requirements', models.TextField(blank=True, help_text='Any special requirements for this guest', null=True)),
                ('is_priority', models.BooleanField(default=False, help_text='Whether this guest has priority seating')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_arrangements', to='base.event')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_arrangements', to='base.guests')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrangements', to='base.table')),
            ],
            options={
                'ordering': ['table__table_number', 'seat_number'],
                'unique_together': {('event', 'guest')},
            },
        ),
        migrations.CreateModel(
            name='TableArrangementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_seat', models.IntegerField(null=True)),
                ('reason', models.TextField(help_text='Reason for the change')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arrangement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='base.tablearrangement')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('previous_table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_arrangements', to='base.table')),
            ],
        ),
        migrations.CreateModel(
            name='TableGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the group (e.g., 'Bride's Family', 'Groom's Colleagues')", max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Special notes about this group', null=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher number means higher priority in table assignment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_groups', to='base.event')),
                ('guests', models.ManyToManyField(related_name='table_groups', to='base.guests')),
                ('preferred_tables', models.ManyToManyField(blank=True, related_name='preferred_by_groups', to='base.table')),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
