# Generated by Django 5.2.2 on 2025-06-08 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0086_organizerreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizerReview',
        ),
    ]
