# Generated by Django 5.2.2 on 2025-06-08 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0087_alter_profile_user'),
        ('base', '0087_delete_organizerreview'),
    ]

    operations = [
    ]
