# Generated by Django 5.2.2 on 2025-06-13 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0088_merge_20250608_0234'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmenu',
            name='category',
            field=models.CharField(choices=[('appetizer', 'Appetizer'), ('main', 'Main'), ('dessert', 'Desert'), ('drink', 'Drink')], default='main', max_length=20),
        ),
        migrations.AddField(
            model_name='eventmenu',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('appetizer', 'Appetizer'), ('main', 'Main'), ('dessert', 'Desert'), ('drink', 'Drink')], default='main', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizer_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.location'),
        ),
    ]
