# Generated by Django 5.2.2 on 2025-06-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0089_eventmenu_category_eventmenu_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guests',
            name='relationship_to_couple',
            field=models.CharField(blank=True, help_text='Relația cu mirii (ex: mireasa, mirele, tatăl miresei, etc.)', max_length=100, null=True),
        ),
    ]
