# Generated by Django 5.2.3 on 2025-06-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0090_guests_relationship_to_couple'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guests',
            name='relationship_to_couple',
        ),
        migrations.AlterField(
            model_name='guestmenu',
            name='menu_choices',
            field=models.ManyToManyField(blank=True, related_name='menu_choices', to='base.menu'),
        ),
        migrations.AlterField(
            model_name='guests',
            name='cuisine_preference',
            field=models.CharField(blank=True, choices=[('no_region', 'No region'), ('italian', 'Italian'), ('french', 'French'), ('mexican', 'Mexican'), ('indian', 'Indian'), ('chinese', 'Chinese'), ('japanese', 'Japanese'), ('american', 'American'), ('mediterranean', 'Mediterranean'), ('romanian', 'Romanian'), ('spanish', 'Spanish'), ('thai', 'Thai'), ('greek', 'Greek'), ('turkish', 'Turkish'), ('german', 'German'), ('korean', 'Korean'), ('vietnamese', 'Vietnamese'), ('lebanese', 'Lebanese'), ('brazilian', 'Brazilian'), ('ethiopian', 'Ethiopian'), ('russian', 'Russian'), ('moroccan', 'Moroccan'), ('caribbean', 'Caribbean'), ('african', 'African'), ('british', 'British'), ('australian', 'Australian'), ('persian', 'Persian'), ('polish', 'Polish'), ('portuguese', 'Portuguese'), ('cuban', 'Cuban'), ('jamaican', 'Jamaican'), ('swedish', 'Swedish'), ('egyptian', 'Egyptian'), ('indonesian', 'Indonesian'), ('malaysian', 'Malaysian'), ('pakistani', 'Pakistani'), ('syrian', 'Syrian'), ('argentinian', 'Argentinian'), ('peruvian', 'Peruvian'), ('filipino', 'Filipino')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='item_cuisine',
            field=models.CharField(choices=[('italian', 'Italian'), ('french', 'French'), ('mexican', 'Mexican'), ('indian', 'Indian'), ('chinese', 'Chinese'), ('japanese', 'Japanese'), ('american', 'American'), ('mediterranean', 'Mediterranean'), ('romanian', 'Romanian'), ('spanish', 'Spanish'), ('thai', 'Thai'), ('greek', 'Greek'), ('turkish', 'Turkish'), ('german', 'German'), ('korean', 'Korean'), ('vietnamese', 'Vietnamese'), ('lebanese', 'Lebanese'), ('brazilian', 'Brazilian'), ('ethiopian', 'Ethiopian'), ('russian', 'Russian'), ('moroccan', 'Moroccan'), ('caribbean', 'Caribbean'), ('african', 'African'), ('british', 'British'), ('australian', 'Australian'), ('persian', 'Persian'), ('polish', 'Polish'), ('portuguese', 'Portuguese'), ('cuban', 'Cuban'), ('jamaican', 'Jamaican'), ('swedish', 'Swedish'), ('egyptian', 'Egyptian'), ('indonesian', 'Indonesian'), ('malaysian', 'Malaysian'), ('pakistani', 'Pakistani'), ('syrian', 'Syrian'), ('argentinian', 'Argentinian'), ('peruvian', 'Peruvian'), ('filipino', 'Filipino')], default='No region', max_length=20),
        ),
    ]
