# Generated by Django 5.2.2 on 2025-06-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0094_add_location_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='cost',
        ),
        migrations.AlterField(
            model_name='location',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='types',
            field=models.ManyToManyField(blank=True, to='base.type'),
        ),
    ]
