# Generated by Django 5.2.2 on 2025-06-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0096_remove_location_email_location_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='position_x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='table',
            name='position_y',
            field=models.FloatField(default=0),
        ),
    ]
