# Generated by Django 5.1.2 on 2025-06-15 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0094_eventgallery'),
        ('base', '0097_add_table_position_fields'),
    ]

    operations = [
    ]
