# Generated by Django 5.1.2 on 2025-06-15 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0098_merge_20250615_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgallery',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='base.event'),
        ),
        migrations.CreateModel(
            name='SpecialElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('entrance', 'Entrance'), ('dancefloor', 'Dance Floor'), ('dj', 'DJ/Band'), ('restrooms', 'Restrooms'), ('bar', 'Bar'), ('kitchen', 'Kitchen'), ('emergency', 'Emergency Exit'), ('photobooth', 'Photo Booth'), ('kids', 'Kids Area')], max_length=32)),
                ('label', models.CharField(blank=True, max_length=64)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_elements', to='base.location')),
            ],
        ),
    ]
