# Generated by Django 5.1.2 on 2025-06-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0099_alter_eventgallery_event_specialelement'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialelement',
            name='rotation',
            field=models.FloatField(default=0),
        ),
    ]
