# Generated by Django 5.1.2 on 2025-06-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0100_specialelement_rotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='rotation',
            field=models.FloatField(default=0),
        ),
    ]
