# Generated by Django 5.2.3 on 2025-06-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0101_table_rotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialelement',
            name='height',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='specialelement',
            name='radius',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='specialelement',
            name='width',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='height',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='radius',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='width',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
