# Generated by Django 5.1.2 on 2025-06-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0103_alter_guestmenu_guest_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='responded',
            field=models.BooleanField(default=False),
        ),
    ]
