# Generated by Django 5.1.2 on 2025-06-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0105_profile_cv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cv_files'),
        ),
    ]
