# Generated by Django 5.2.3 on 2025-06-17 15:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0107_alter_profile_cv_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_common', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Medical Condition',
                'verbose_name_plural': 'Medical Conditions',
            },
        ),
        migrations.RemoveField(
            model_name='guests',
            name='vegan',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='item_vegan',
        ),
        migrations.AddField(
            model_name='guests',
            name='custom_medical_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guests',
            name='diet_preference',
            field=models.CharField(choices=[('none', 'No specific diet'), ('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('pescatarian', 'Pescatarian'), ('low_carb', 'Low-carb'), ('keto', 'Keto'), ('halal', 'Halal'), ('kosher', 'Kosher')], default='none', max_length=15),
        ),
        migrations.AddField(
            model_name='guests',
            name='spicy_food',
            field=models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='menu',
            name='diet_type',
            field=models.CharField(choices=[('none', 'No specific diet'), ('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('pescatarian', 'Pescatarian'), ('low_carb', 'Low-carb'), ('keto', 'Keto'), ('halal', 'Halal'), ('kosher', 'Kosher')], default='none', max_length=15),
        ),
        migrations.AddField(
            model_name='menu',
            name='spicy_level',
            field=models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='none', max_length=10),
        ),
        migrations.CreateModel(
            name='EventBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_rental_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ceremony_location_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('furniture_rental_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('decorations_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('wedding_dress_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('groom_suit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('accessories_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shoes_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('photographer_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('videographer_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('photo_booth_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('band_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dj_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sound_system_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hair_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('makeup_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('spa_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bouquet_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('centerpieces_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ceremony_flowers_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('food_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('beverages_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cake_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('snacks_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invitations_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('favors_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('thank_you_cards_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('wedding_car_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('guest_shuttle_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('insurance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('license_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('planner_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('organizer_payment_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eventbudget', to='base.event')),
            ],
        ),
        migrations.AddField(
            model_name='guests',
            name='medical_conditions',
            field=models.ManyToManyField(blank=True, to='base.medicalcondition'),
        ),
        migrations.CreateModel(
            name='MenuRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_ratings', to='base.guests')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='base.menu')),
            ],
            options={
                'unique_together': {('guest', 'menu_item')},
            },
        ),
    ]
