# Generated by Django 5.2.3 on 2025-06-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0108_medicalcondition_remove_guests_vegan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='stars',
            new_name='organizer_stars',
        ),
        migrations.AddField(
            model_name='review',
            name='location_stars',
            field=models.IntegerField(choices=[(1, '1 stele'), (2, '2 stele'), (3, '3 stele'), (4, '4 stele'), (5, '5 stele')], default=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
