# Generated by Django 5.2.3 on 2025-06-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0110_review_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='guests',
            name='nutrition_goal',
            field=models.CharField(blank=True, choices=[('none', 'No specific goal'), ('high_protein', 'High protein'), ('low_fat', 'Low fat'), ('low_sugar', 'Low sugar'), ('balanced', 'Balanced')], default='none', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='guests',
            name='preferred_course',
            field=models.CharField(blank=True, choices=[('appetizer', 'Appetizer'), ('main', 'Main'), ('dessert', 'Dessert'), ('drink', 'Drink')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guests',
            name='temp_preference',
            field=models.CharField(blank=True, choices=[('hot', 'Hot'), ('cold', 'Cold')], default='hot', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='guests',
            name='texture_preference',
            field=models.CharField(blank=True, choices=[('none', 'No preference'), ('crunchy', 'Crunchy'), ('creamy', 'Creamy'), ('juicy', 'Juicy'), ('soft', 'Soft')], default='none', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='calories',
            field=models.PositiveIntegerField(blank=True, help_text='kcal per serving', null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='carbs_g',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='cooking_method',
            field=models.CharField(blank=True, choices=[('grill', 'Grill'), ('bake', 'Bake'), ('fry', 'Fry'), ('steam', 'Steam'), ('boil', 'Boil'), ('raw', 'Raw')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='fat_g',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='protein_g',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='serving_temp',
            field=models.CharField(choices=[('hot', 'Hot'), ('cold', 'Cold')], default='hot', max_length=5),
        ),
    ]
