# Generated by Django 5.2.3 on 2025-06-18 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0111_guests_nutrition_goal_guests_preferred_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestmenu',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='base.event'),
        ),
    ]
