# Generated by Django 5.2.3 on 2025-06-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0112_alter_guestmenu_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='spicy_food',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='none', max_length=10, null=True),
        ),
    ]
