# Generated by Django 5.1.2 on 2025-06-20 18:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0113_alter_guests_spicy_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimisedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_location_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cost locație inițială')),
                ('optimized_location_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cost locație optimizată')),
                ('event_gross_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Profit brut eveniment')),
                ('profit_net_old', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Profit net inițial')),
                ('profit_net_new', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Profit net optimizat')),
                ('optimized_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data optimizării')),
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='ID Rulare Optimizare')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimisation_results', to='base.event', verbose_name='Eveniment')),
                ('optimized_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optimised_new_events', to='base.location', verbose_name='Locație optimizată')),
                ('original_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optimised_original_events', to='base.location', verbose_name='Locație inițială')),
            ],
            options={
                'verbose_name': 'Eveniment Optimizat',
                'verbose_name_plural': 'Evenimente Optimizate',
                'ordering': ['-optimized_at', 'event__event_date'],
            },
        ),
    ]
