# Generated by Django 5.1.2 on 2025-06-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0115_profile_welcome_email_sent_alter_specialelement_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofit',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
