# Generated by Django 5.1.2 on 2025-06-26 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0115_profile_welcome_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialelement',
            name='type',
            field=models.CharField(choices=[('entrance', 'Entrance'), ('dancefloor', 'Dance Floor'), ('dj', 'DJ/Band'), ('restrooms', 'Restrooms'), ('bar', 'Bar'), ('kitchen', 'Kitchen'), ('emergency', 'Emergency Exit'), ('photobooth', 'Photo Booth'), ('kids', 'Kids Area'), ('custom', 'Custom')], max_length=32),
        ),
        migrations.CreateModel(
            name='FaceEncoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_encodings', to='base.event')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_encodings', to='base.profile')),
            ],
            options={
                'verbose_name': 'Face Encoding',
                'verbose_name_plural': 'Face Encodings',
                'unique_together': {('profile', 'event')},
            },
        ),
    ]
