# Generated by Django 5.1.2 on 2025-06-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0116_alter_companyprofit_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
