# Generated by Django 5.1.2 on 2025-06-26 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0116_alter_specialelement_type_eventlayout_faceencoding'),
        ('base', '0117_alter_companyprofit_created_at'),
    ]

    operations = [
    ]
