# Generated by Django 5.1.2 on 2025-06-26 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0118_merge_20250626_1846'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventLayout',
        ),
    ]
