# Generated by Django 5.1.2 on 2025-06-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0119_delete_eventlayout'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommenderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_trained_at', models.DateTimeField(auto_now_add=True)),
                ('last_rating_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Recommender Status',
                'verbose_name_plural': 'Recommender Status',
            },
        ),
    ]
